apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zjyscontrollers.groupt
spec:
  preserveUnknownFields: false
  group: groupt
  version: v1
  names:
    kind: ZjyController
    listKind: ZjyControllerList
    plural: zjycontrollers
    shortNames:
    - zjy
    singular: zjycontroller
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.replicas
      name: REPLICAS
      type: integer
    - jsonPath: .spec.template.name
      name: NAME
      type: string
    - jsonPath: .spec.template.gender
      name: GENDER
      type: integer
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description : 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources' 
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              replicas:
                nullable: true
                type: integer
              template:
                properties:
                  name: 
                    type: string
                  gender:
                    type: string
        type: object
    served: true
    storage: true

          

